language: php

php:
  - 5.6

# test only master (+ Pull requests)
branches:
  only:
    - master

env:
  matrix:
    - TARGET="phpunit"
    - TARGET="phpspec"
    - TARGET="behat"

# setup requirements for running unit tests
before_script:
  - composer install
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:create
  - cd vendor/bdunogier/subber && composer install && cd -

# execute phpunit as the script command
script:
  - if [ "$TARGET" == "phpunit" ] ; then cd vendor/bdunogier/subber && php -d date.timezone=$TEST_TIMEZONE ./bin/phpunit tests/; fi
  - if [ "$TARGET" == "phpspec" ] ; then cd vendor/bdunogier/subber && php ./bin/phpspec run --format=pretty; fi
  - if [ "$TARGET" == "behat" ]   ; then php app/console --env=dev server:start; ./bin/behat -c behat.yml.dist; fi

# disable mail notifications
notification:
  email: false
