language: php

php:
  - 5.6

# test only master (+ Pull requests)
branches:
  only:
    - master

env:
  matrix:
    - TARGET="phpunit"
    - TARGET="phpspec"

# setup requirements for running unit tests
before_script:
  - cd vendor/bdunogier/subber
  - composer install

# execute phpunit as the script command
script:
  - if [ "$TARGET" == "phpunit" ] ; then composer require phpunit/phpunit; php -d date.timezone=$TEST_TIMEZONE ./bin/phpunit tests/; fi
  - if [ "$TARGET" == "phpspec" ] ; then php ./bin/phpspec run --format=pretty; fi

# disable mail notifications
notification:
  email: false
