imports:
    - { resource: parameters.yml }
#    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    filters:
        less:
            node: %executable.node.path%
            node_paths: [%executable.node.modules_path%]
            apply_to: "\.less$"
        cssrewrite: ~
braincrafted_bootstrap:
    less_filter: less

# Doctrine Configuration
doctrine:
    dbal:
        connections:

            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                path:     "%database_path%"
                charset:  UTF8

#            sabnzbd_history:
#                driver:   "%sabnzbd_history.database_driver%"
#                host:     "%sabnzbd_history.database_host%"
#                port:     "%sabnzbd_history.database_port%"
#                dbname:   "%sabnzbd_history.database_name%"
#                user:     "%sabnzbd_history.database_user%"
#                password: "%sabnzbd_history.database_password%"
#                path:     "%sabnzbd_history.database_path%"
#                charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"

        entity_managers:
            default:
                connection: default
                mappings:
                    subber:
                        type: annotation
                        dir: %kernel.root_dir%/../vendor/bdunogier/subber/lib/Entity
                        prefix: BD\Subber\Entity
                        alias: Subber
                        is_bundle: false
